AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instance created from Launch Template (fixed single instance)

Parameters:
  LaunchTemplateId:
    Type: String
  Version:
    Type: String

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateId
        Version: !Ref Version
      Tags:
        - Key: Name
          Value: fixed-launch-template-instance

  InstanceEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt InstanceEIP.AllocationId
      InstanceId:   !Ref EC2Instance
      

Outputs:
  InstanceId:
    Value: !Ref EC2Instance
  PublicIp:
    Value: !GetAtt EC2Instance.PublicIp
